---
#
#   FactionsPE: PocketMine-MP Plugin
#   Copyright (C) 2017  Chris Prime
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Plugin language
# en - English (USA)
# lv - Latvian
language: en

# Economy
economy-support: false
economy-plugin: "EconomyAPI"

# Form support, adds UI to commands. (W.I.P. Untested, unstable, in-dev = will crash)
enable-form-menus: false

# Data provider settings
# Supported types as of now: yaml, json, mysql
data-provider:
  type: "yaml"
  mysql:
    host: 127.0.0.1
    user: guest
    password: secret
    database: factions-pe

# Chat
# Set this to true if you want to use default chat formatter
force-chat-formatter: false

# Should inactive factions be disbanded?
purge-inactive-factions: true
# Purge faction if (last online - now) >= purge-after
# Time in seconds
# default: week (604800)
purge-after: 604800

# Claim size (1 = 128; 2 = 64; 3 = 32; 4 = 16 (default); 5 => 8; 6 => 4);
claim-size: 4

# Scoreboard.
#
# Available variables:
# <padding> = Align everything to the left
# :faction = Your faction's name
# :name = Your display name
# :online-members = Number of your teammates online
# :max-members = Total amount of players in your faction
# :power = Current power level
# :here-faction = Name of faction, on land you're standing on
# <here-color> = relationship color of the land you're standing on
# :direction = North, South, East, West
# :short-direction = N, S, E, W
# :x, :y, :z = your coordinates
scoreboard:
  enabled: true
  title: "----- <gold>Factions <white>-----"
  faction:
    - "Faction:<padding> <red>:faction"
    - "Members:<padding> <gold>:online-members<white>/<gold>:max-members"
    - "Power:<padding> <gold>:power<white>/<gold>:max-power"
    - "Here:<padding> <here-color>:here-faction"
    - ""
    - ""
    - "X: <gray>:x <white>Y: <gray>:y <white>Z: <gray>:z <white>(<gray>:short-direction<white>)<padding>"
  factionless:
    - "Power:<padding> <gold>:power<white>/<gold>:max-power"
    - "Here:<padding> <here-color>:here-faction"
    - ""
    - ""
    - "X: <gray>:x <white>Y: <gray>:y <white>Z: <gray>:z<white> (<gray>:short-direction<white>)<padding>"

# Gameplay settings
gameplay:
  # Enable the ability for players to fly in their claimed lands (/f fly)
  fly: false
  hud:
    enabled: false
    popup: "》 Power: &6{POWER}&f/&6{MAXPOWER} &8|&f Money: &6{MU}{MONEY} &8|&f Faction: &6{FACTION} &8|&f Faction power: &6{F-POWER}&f/&6{MAXF-POWER}&f 《"
    tip: null
  # These are messages you'll receive on certain events. They can be switched on/off
  log:
    faction-disband: true
    faction-new-leader: true
    faction-creation: true
    member-leave: true
    member-join: true
    member-kick: true
    override: true
    faction-chat: true
    perm-change: true
  # Power settings, for players and factions
  power:
    player:
      # Maximum possible amount of power for player
      max: 100
      # Minimum possible amount of power for player
      min: -100
      # Power decrease per death
      per-death: 5
      # Power decrease per claim
      per-claim: 5
      # How much power will player gain every update ?
      per-update: 1
      # Default power value for player
      default: 10
    # Power increase interval in minutes
    update-every: 10
    # Should power increase time by time ?
    update-enabled: true
  faction:
    # Automatically disband factions without any members (except special ones)
    destroy-empty-factions: true
    # How many members can one faction hold?
    member-limit: 10
    # Idk what this means :D. (I still don't know - 2018 August)
    # No idea ( - 2020 September)
    disable-permanent-leader-promotion: true
  faction-name:
    # Maxmimum name length
    max-length: 12
    # Minimum name length
    min-length: 3
  price:
    # If economy is enabled, you can set how much should players pay for creating a new faction
    faction-creation: 5000
  home:
    # Enable faction homes
    enabled: true
    # Automatically teleport to faction home after respawn ?
    teleport-to-on-death: true
    # Is "/f home" enabled?
    teleport-command-enabled: true
    # Home must be located in faction territory ?
    must-be-in-claimed-territories: true
    # Can members teleport to faction home while being on enemy land ?
    teleport-allowed-from-enemy-territory: false
    # Is teleporting throughout different worlds allowed ?
    teleport-allowed-from-different-world: true
    # What is minimum allowed distance, between player and enemy to allow teleportation ? (blocks)
    teleport-allowed-enemy-distance: 10
    # Ignore above setting, if you are in your own land ?
    teleport-ignore-enemies-if-in-own-territory: false
  # Can player leave faction with negative power level ?
  can-leave-with-negative-power: false
  # Can player join new faction with negative power level ?
  can-join-with-negative-power: false
  # Built-in chat formatter settings. Color tags are hardcoded, sorry!
  chat:
    player: "{NAME}: {MESSAGE}"
    member: "<gray>[<gold>{BADGE}<white>{FACTION}<gray>]<white> {NAME}: {MESSAGE}"
    member-title: "<gray>[<gold>{BADGE}<white>{FACTION}<gray>]<white>[{TITLE}]<white> {NAME}: {MESSAGE}"
    faction-chat: "<gray><bold>(<red>fac<gray><bold>) <red>{BADGE}<gray><{NAME}<gray>: <red>{MESSAGE}"
    badge:
      leader: "**"
      officer: "*"
      member: "+"
      recruit: "-"
  color:
    enemy: "<red>"
    ally: "<green>"
    truce: "<gold>"
    neutral: "<white>"
  # Where PVP is enabled and no default rules are checked? This means that PVP will be allowed no matter what
  worlds-pvp-rules-enabled: []
  # Where land can be claimed ?
  worlds-claiming-enabled: [world]
  # Where players can loose their power ?
  worlds-power-loss-enabled: [world]
  # Where players can gain power in pvp ?
  world-power-gain-enabled: [world]
  # Can players gain power by killing allies ?
  allow-ally-kill-bonus: false
  # Super-users list here
  players-who-bypass-all-protection: []
  # Can players with faction attack other faction-less players ? 
  can-member-attack-factionless: true
  # Can players with no faction deal no damage to others ?
  can-hurt-while-factionless: true
  # Can members of faction kill faction-less player if he is in their territory ?
  enable-pvp-against-factionless-in-attackers-land: true
  # Can faction-less players attack each other?
  enable-pvp-between-factionless-players: true
  # Broadcast friendly fire (teammate killed teammate) (Options: all, faction, off or false)
  broadcast-friendly-fire: 'faction'
  # Should blocks break even tho TNT exploded in water ?
  handle-exploit-tnt-water-log: true
  # Show faction's motd when member joins
  show-motd-on-join: true
  # Minimum member count to start claiming land
  claims-require-min-faction-members: 1
  # Maximum land count
  claimed-lands-max: 99999999
  # Should next claim must be connected with previous ?
  claims-must-be-connected: true
  # Can setting above be ignored if over-claiming ?
  claims-can-be-unconnected-if-owned-by-other-faction: true
  # Is over-claiming allowed ?
  claiming-from-others-allowed: true
  # Pain build damage
  action-denied-pain-amount: 1
  # Protection from liquids
  protection-liquid-flow-enabled: true
  # These values as of < v1.0.0 can't be changed.
  # They are hard-coded into code
  materials-edit-on-interact: []
  materials-container: []
  materials-doors: []
  materials-edit-tools: []
  materials-edit-tools-dupe-bug: []
  # Should, tip appear when plot owner changes ?
  send-plot-faction-description: true
...
